# Generated by Django 4.2.7 on 2025-05-19 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pawsitive", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volunteerapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Volunteer Application",
                "verbose_name_plural": "Volunteer Applications",
            },
        ),
    ]
