# Generated by Django 4.2.7 on 2025-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pawsitive", "0002_alter_volunteerapplication_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerapplication",
            name="interests",
            field=models.JSONField(blank=True, default=list, verbose_name="Interests"),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Location"
            ),
        ),
    ]
